/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.Tool.Templateconflict;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

import com.Tool.Templateconflict.TemplateConflictEliminator;

/**
 *
 * @author anustiya_C01
 */
public class Toolui extends javax.swing.JFrame {

    /**
     * Creates new form Toolui
     */
    public Toolui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnFromGitButton = new javax.swing.JButton();
        btnEliminateConflicts = new javax.swing.JButton();
        btnFromLocalFolder = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        btnListOfIncluded = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Template Conflict Eliminator Tool");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnFromGitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFromGitButton.setText("From GIT Folder");

        btnEliminateConflicts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminateConflicts.setText("Eliminate Conflicts");

        btnFromLocalFolder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFromLocalFolder.setText("From Local Folder");

        resetBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resetBtn.setText("Reset");

        exitBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnListOfIncluded.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnListOfIncluded.setText("List of Included Stylesheets");
        
        scrollPane = new JScrollPane();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
        					.addComponent(btnEliminateConflicts, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(btnListOfIncluded, GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        					.addComponent(btnFromLocalFolder, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(btnFromGitButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addComponent(resetBtn, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(exitBtn, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE)))
        			.addGap(53)
        			.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 398, GroupLayout.PREFERRED_SIZE)
        			.addGap(22))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 245, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addComponent(btnFromGitButton, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(btnFromLocalFolder, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(btnListOfIncluded, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(btnEliminateConflicts, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(resetBtn, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        						.addComponent(exitBtn, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap(14, Short.MAX_VALUE))
        );
        
        textArea = new JTextArea();
        scrollPane.setViewportView(textArea);
        jPanel2.setLayout(jPanel2Layout);

        jPanel4.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.buttonShadow"));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Template Conflict Eliminator Tool");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        
		btnFromGitButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// Handle open button action.
				if (e.getSource() == btnFromGitButton) {
					File gitFolder = new File("C:\\raja\\AnuTool\\Template conflict\\anu\\Apple.xsl").getParentFile();
					try {
						textArea.setText(gitFolder.getPath().toString());
						btnListOfIncluded.setEnabled(true);
						btnEliminateConflicts.setEnabled(true);
					} catch (Exception e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
					// TemplateConflictEliminator.eliminateTempalateConflicts(gitFolder);
				}
			}
		});

		btnFromLocalFolder.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// Handle open button action.
				if (e.getSource() == btnFromLocalFolder) {
					int returnVal = fileChooser.showOpenDialog(Toolui.this);

					if (returnVal == JFileChooser.APPROVE_OPTION) {
						File file = fileChooser.getSelectedFile();
						// This is where a real application would open the file.
						textArea.setText(file.getAbsolutePath());
						btnListOfIncluded.setEnabled(true);
						btnEliminateConflicts.setEnabled(true);
						final JComponent[] inputs = new JComponent[] { new JLabel(
								"<html>Would you like to process all the Stylesheets in the folder of the File you Chose? <br>Saying No will process the selected File alone</html>") };
						int result = JOptionPane.showConfirmDialog(null, inputs, "My custom dialog",
								JOptionPane.OK_OPTION);
						if (result == JOptionPane.OK_OPTION) {
							try {
								// Desktop.getDesktop().open(new File(new
								// File(textArea.getText()).getParent()));
								// TemplateConflictEliminator.eliminateTempalateConflicts(file.getParentFile());

								textArea.setText((file.getParentFile()).getAbsolutePath());

							} catch (Exception ex) {
								System.err.println("Cant open the stylesheet folder");
							}
						} else {
							textArea.setText(file.getAbsolutePath());
							// TemplateConflictEliminator.eliminateTempalateConflicts(file);
						}
					}
				}
			}
		});

		btnListOfIncluded.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// Handle open button action.
				if (e.getSource() == btnListOfIncluded) {
					// Desktop.getDesktop().open(new File(new
					// File(textArea.getText()).getParent()));
					textArea.setText(TemplateConflictEliminator
							.eliminateTempalateConflicts(new File(textArea.getText()), true));
					btnListOfIncluded.setEnabled(false);
					btnEliminateConflicts.setEnabled(false);

				}
			}
		});

		btnEliminateConflicts.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// Handle open button action.
				if (e.getSource() == btnEliminateConflicts) {

					System.out.println(e);
					// Desktop.getDesktop().open(new File(new
					// File(textArea.getText()).getParent()));

					File openfile = new File(textArea.getText());

					textArea.setText(TemplateConflictEliminator.eliminateTempalateConflicts(openfile, false));
					btnListOfIncluded.setEnabled(false);
					btnEliminateConflicts.setEnabled(false);
					final JComponent[] inputs = new JComponent[] { new JLabel(
							"Your Stylesheet files are updated with priorities, please click YES to view them") };
					int result = JOptionPane.showConfirmDialog(null, inputs, "My custom dialog", JOptionPane.OK_OPTION);
					if (result == JOptionPane.OK_OPTION) {
						try {

							if (!openfile.isDirectory() && openfile.isFile()) {

								openfile = openfile.getParentFile();
							}
							Desktop.getDesktop().open(openfile);
						} catch (Exception ex) {
							System.err.println("Cant open the stylesheet folder");
						}
					} else {
						System.out.println("User canceled / closed the dialog, result = " + result);
					}

				}
			}
		});

		resetBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				textArea.setText("");
				btnListOfIncluded.setEnabled(true);
				btnEliminateConflicts.setEnabled(true);
			}
		});

		exitBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				System.exit(0);
			}
		});
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toolui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toolui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toolui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toolui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Toolui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFromGitButton;
    private javax.swing.JButton btnEliminateConflicts;
    private javax.swing.JButton btnFromLocalFolder;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton btnListOfIncluded;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private static JFileChooser fileChooser = new JFileChooser();
    private JScrollPane scrollPane;
    private JTextArea textArea;
    // End of variables declaration//GEN-END:variables
    
}
